config/routes.rb
Rails.application.routes.draw do
  get 'collaborators/create'

  get 'collaborators/destroy'

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  resources :charges, only: [:new, :create]
  resources :downgrade, only: [:destroy]

  devise_for :users
  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
   belongs_to :wiki
   belongs_to :user

   def self.update_collaborators(collaborator_string)
      return Collaborator.none if collaborator_string.blank?
        collaborator_string.split(",").map do |collaborator|
        Collaborator.find_or_create_by(email: collaborator.strip)
      end
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  has_many :wikis
  has_many :collaborators, dependent: :destroy


  after_initialize :initialize_role
  
  def self.going_public(user)
    @wikis = user.wikis.where(private: true)
    @wikis.each do |wiki|
      wiki.update_attribute(:private, false)
    end
  end

  private

  def initialize_role
    self.role ||= :standard
  end

  enum role: [:standard, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user, optional: true

  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
  
  after_initialize :initialize_role

  private

  def initialize_role
    self.private = false if self.private.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
     customer = Stripe::Customer.create(
       email: current_user.email,
       card: params[:stripeToken]
     )

     charge = Stripe::Charge.create(
       customer: customer.id,
       amount: 15_00,
       description: "BigMoney Membership - #{current_user.email}",
       currency: 'usd'
     )

     flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
     current_user.premium!
     redirect_to wikis_path

     rescue Stripe::CardError => e
       flash[:alert] = e.message
       redirect_to new_charge_path
  end

  def new
     @stripe_btn_data = {
       key: "#{ Rails.configuration.stripe[:publishable_key] }",
       description: "BigMoney Membership - #{current_user.email}",
       amount: 15_00
     }
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find_by_email(params[:collaborator][:user])

   @collaborator = @wiki.collaborators.new(wiki_id: @wiki.id, user_id: @user.id)

      if @collaborator.save
        flash[:notice] = "User added"
      else
        flash[:error] = "Error"
      end
      redirect_to @wiki


  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Delete successfull"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error"
      redirect_to @wiki
    end
  end
end

app/controllers/downgrade_controller.rb
class DowngradeController < ApplicationController
  def destroy
    flash[:notice] = "You have downgraded your account and your wikis are now publicized."
    current_user.standard!
    current_user.wikis.update_all(:private => false)
    redirect_to wikis_path
  end
end

app/controllers/rake_controller.rb
class RakeController < ApplicationController
  def db:migrate
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :wikis, dependent: :destroy
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
     @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    if current_user.present?
      collaborators = []
      @wiki.collaborators.each do |collaborator|
        collaborators << collaborator.email
      end
    unless (@wiki.private == false) || @wiki.user == current_user || collaborators.include?(current_user.email) || current_user.admin?
        flash[:alert] = "You are not authorized to view this wiki."
        redirect_to new_charge_path
      end
    else
      flash[:alert] = "You are not authorized to view this wiki."
      redirect_to new_user_registration_path
    end
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      @wiki.collaborators = Collaborator.update_collaborators(params[:wiki][:collaborators])
      flash[:notice] = "Your wiki was saved successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving your wiki. Please try again later."
      render :new
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki

    if @wiki.save && (@wiki.user == current_user || current_user.admin?)
      @wiki.collaborators = Collaborator.update_collaborators(params[:wiki][:collaborators])
      flash[:notice] = "Wiki was updated successfully."
      redirect_to @wiki
    elsif @wiki.save
      flash[:notice] = "Wiki was updated successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/downgrade_helper.rb
module DowngradeHelper
end

app/helpers/rake_helper.rb
module RakeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
    def user_is_authorized_to_create?
        current_user && (current_user.admin? || current_user.premium?)
    end
    
    def user_is_authorized_to_update?
        current_user
    end
    
    def user_is_authorized_to_delete?
        current_user && (current_user == @wiki.user || current_user.admin?)
    end

    def markdown(text)
        extensions = [:tables, :fenced_code_blocks, :autolink, :strikethrough, :underline, :highlight, :quote, :footnotes]
        Markdown.new(text, *extensions).to_html.html_safe
    end
end

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/collaborators/_form.html.erb
<% if @wiki.private? && policy(@wiki).destroy?  %>

  <%= form_for [wiki, Collaborator.new] do |f| %>
    Add Collaborators using their Email
     <%= f.label :user %>
     <%= f.text_field :user, placeholder: "User's Email" %>

     <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>
<% end %>

app/views/collaborators/_list.html.erb
<div class="container">
  <div class="row">
    <h2>Collaborators:</h2>
    <% @wiki.collaborators.each do |collaborator| %>
      <p>
        <%= collaborator.user.email %>
        <!-- delete collaborator option only available to creator -->
        <% if @wiki.user == current_user %>
          <%= link_to "", [collaborator], method: :delete, class: 'btn btn-danger delete'%>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/collaborators/create.html.erb
<h1>Collaborators#create</h1>
<p>Find me in app/views/collaborators/create.html.erb</p>

app/views/collaborators/destroy.html.erb
<h1>Collaborators#destroy</h1>
<p>Find me in app/views/collaborators/destroy.html.erb</p>

app/views/downgrade/new.html.erb
<%= form_tag downgrade_path do %>
  <h4>All your private wikis will be publicized if your account is downgraded.</h4>
  <%= link_to "Downgrade My Account!", method: :destroy, class: 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>
      <div class="user-info pull-right">
        <% if user_signed_in? %>
           Signed in as: <strong><%= current_user.email %></strong> |
           <ul class="nav nav-tabs">
             <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
             <% if current_user.standard? %>
                <li><%= link_to 'Upgrade Your Account', new_charge_path, :class => 'navbar-link' %></li>
             <% elsif current_user.premium? %>
                <li><%= link_to 'Downgrade Your Account', downgrade_path(current_user), method: :delete, :class => 'navbar-link' %></li>
             <% end %>
        <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> - </li>
              <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
      </div>
      </ul>
      
       <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
     <%= yield %>
    </div>
  </body>
</html>

app/views/rake/db:migrate.html.erb
<h1>Rake#db:migrate</h1>
<p>Find me in app/views/rake/db:migrate.html.erb</p>

app/views/users/new.html.erb
 <h2>Sign up</h2>
 
 <div class="row">
   <div class="col-md-8">
     <%= form_for @user do |f| %>
       <% if @user.errors.any? %>
         <div class="alert alert-danger">
           <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
           <ul>
             <% @user.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
       <% end %>
       <%= form_group_tag(@user.errors[:name]) do %>
         <%= f.label :name %>
         <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
       <% end %>
       <%= form_group_tag(@user.errors[:email]) do %>
         <%= f.label :email %>
         <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password]) do %>
         <%= f.label :password %>
         <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password_confirmation]) do %>
         <%= f.label :password_confirmation %>
         <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
       <% end %>
       <div class="form-group">
         <%= f.submit "Sign up", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/edit.html.erb
<% if user_is_authorized_to_update? %>
    <h1>Edit Wiki</h1>

    <div class="row">
        <div class="col-md-4">
            <p>Wiki Commandments</p>
            <ul>
                <li>Make it awesome~</li>
                <li>Be clever!</li>
            </ul>
        </div>
        <div class="col-md-8">
            <%= form_for @wiki do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
                </div>
                <div class="form-group">
                    <%= f.label :body %>
                    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
                </div>
                <% if current_user.admin? || current_user.premium? %>
                <div class="form-group">
                    <%= f.label :private, class: 'checkbox' do %>
                        <%= f.check_box :private %> Private topic
                    <% end %>
                </div>              
                <% end %>
              
                <div class="form-group">
                    <%= f.submit "Save", class: 'btn btn-success' %>
                </div>
            <% end %>

         collaborators: <%= @wiki.collaborators.count %>
         <%= render partial: 'collaborators/form', locals: { wiki: @wiki } %>
     
        </div>
    </div>
<% end %>

app/views/wikis/index.html.erb
<div class="container">
  <div class="row heading">
    <div class="col-md-12">
      <h1>Public Wikis</h1>
    </div>
  </div>

  <div class="row new-wiki">
    <div class="col-md-12">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <% @wikis.each do |wiki| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading wiki-title">
              <%= link_to wiki.title, wiki %>
              <br>
              <small>
                Owner: <%= wiki.user.email%>
              </small>
            </h4>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/wikis/new.html.erb
<% if user_is_authorized_to_create? %>
    <h1>New Wiki</h1>
    <div class="row">
        <div class="col-md-4">
            <p>Wiki Guidelines:</p>
            <ul>
                <li>Be a nice jerk.</li>
                <li>Be like me.</li>
            </ul>
        </div>
        <div class="col-md-8">
            <%= form_for @wiki do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
                </div>
                <div class="form-group">
                    <%= f.label :body %>
                    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
                </div>
                <% if current_user.admin? || current_user.premium? %>
                    <div class="form-group">
                      <%= f.label :private, class: 'checkbox' do %>
                        <%= f.check_box :private %>Make it private
                    <% end %>
                <% end %>
                <div class="form-group">
                    <%= render partial: 'collaborators/form', locals: { f: f, collaborators: @wiki.collaborators } %>
                </div>
                <div class="form-group">
                    <%= f.submit "Save", class: 'btn btn-success' %>                
                </div>
            <% end %>
        </div>
    </div>
<% end %>

app/views/wikis/show.html.erb
<div>
  <h1><%= @wiki.title %></h1>
  <small>
       submitted <%= time_ago_in_words(@wiki.created_at) %> ago
  </small>
  <p> Private? <%= @wiki.private %></p>
  <p> Owner: <%= @wiki.user.email %></p>
  <%= render partial: 'collaborators/list' %>
</div>

 <div class="row">
   <div class="col-md-8">
      <p><%= markdown(@wiki.body) %></p>
   </div>
   <div class="col-md-4">
     <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
     <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
   </div>
 </div>


 <div class="container">
   <div class="row">
     <h4>List of Wiki Collaborators:</h4>
     <% @wiki.collaborators.each do |collaborator| %>
       <p>
         <%= collaborator.user.email %> <small><em> - user ID: <%= collaborator.user.id%></em></small>
         <!-- delete collaborator option only available to creator -->
         <% if @wiki.user.premium? || @wiki.user.admin? %>
           <%= link_to "Remove", @collaborator, method: :delete, class: 'glyphicon glyphicon-ok' %>
         <% end %>
       </p>
     <% end %>
   </div>
 </div>